### PR TITLE
Change chrome namespace to browser everywhere

### PR DESCRIPTION
**Pull request by felfert**
A trivial one.
Use browser.* namespace everywhere.

### CODE REVIEW

**Comment by DASPRiD** [comment]
Was the chrome namespace deprecated? Or what's the reason for the switch? :)

**Comment by felfert** [comment]
browser is actually in the webext spec. There exist bugs in chrome's bugtracker to change their API.
See also: https://github.com/mozilla/webextension-polyfill

**Comment by DASPRiD** [comment]
Alright, it's in – but no reason to make a new release out of that yet :)

**Comment by felfert** [comment]
> Alright, it's in – but no reason to make a new release out of that yet :)

LOL :-D didn't expect it

**Comment by felfert** [comment]
There will be 2 more soon, but nothing really exciting. So no expectations as well ;-)

**Comment by DASPRiD** [comment]
As I wrote on the other issue, I'm on vacation till the end of the week, so don't expect any more merges till then ;)

**Comment by felfert** [comment]
Yeah no problem - have a nice vacation!

**Pull request merged**
