### PR TITLE
 Send cookies with torrent request.

### PR DESCRIPTION
**Pull request by z0rb**
Issue #9 

Also: Fix torrentToWeb variable redeclaration.
It was not possible to install the extension. Firefox was throwing an error and the context menu entry wasn't shown. Once the redeclaration of the torrentToWeb variable was removed the add-on installed as expected. Not sure what the redeclarations were there for. If this is wrong I'll fix it...

### CODE REVIEW

**Comment by DASPRiD** [comment]
I'm wondering, which Firefox version are you using? The `let` statements never caused a problem for me or anyone else, and I always download torrents with this from login-protected sites.

**Comment by z0rbas** [comment]
I'm currently on version 58.0.2 on linux.

The `let` statements have nothing to do with the authentication of the request. As stated in the initial issue I was getting a 404 response from the torrent site. This is normal for the site when you try to use a link without being authenticated. I wanted to test if the `XMLHttpRequest.withCredentials` property will cause the request to have the necessary cookies. (Which it did...)

In order to test the parameter I cloned the code and tried "load temporary add-on" from about:debugging. The add-on wasn't installed correctly and the context menu entry didn't appear. Then I installed web-ext and tried debugging that way, but the result was the same. Pbroc had the same issue in the other open pull-request: https://github.com/DASPRiD/Torrent-to-Web/pull/2#issuecomment-347167250
Coincidentally he replaced the `let` with a `var` too. Perhaps a more correct approach would be to use javascript modules. Maybe the `let`s don't cause problems once the add-on is packaged and signed ...

After this fix came the meat of the assignment. I just set `XMLHttpRequest.withCredentials` to `true` and the request to the torrent site went through and added it to rutorrent.

**Comment by z0rb** [comment]
Well, I think I found the actual culprit. Did some further digging and it turned out that the debugging firefox instance that was started by web-ext didn't have the same config as my usual firefox instance. I always set accepting third party cookies to "never". The extension worked in the clean instance because third party cookies were enabled.

The bug describing the behavior: https://bugzilla.mozilla.org/show_bug.cgi?id=1322113

A possible fix/workaround: https://discourse.mozilla.org/t/webextension-xmlhttprequest-issues-no-cookies-or-referrer-solved/11224/18

Version 59 changes list WebExtension cookie handling: https://blog.mozilla.org/addons/2018/01/26/extensions-firefox-59/

I have added my tracker to the cookie exceptions list in preferences and the extension behaves as it should. So I guess it's best to wait for a fix from mozilla and apply whatever manifest or code changes are required. (The workaround described in the link above could fix the behavior until mozilla fixes the cause.)

**Comment by DASPRiD** [comment]
Oh, thanks for investigating, that's a really good find! So shall we just hold off on this issue for now and wait for it to be fixed? I think this is a very rare case to run into for users.

**Comment by z0rb** [comment]
I just tested with FF Developer edition 59.0b10 and the issue was still there. Probably best to wait until 13.3.2018 for the 59 release. The bug I linked will probably get updated if the issue gets fixed or new features are introduced which help with a fix. Otherwise the workaround might do the trick.

Turning third party cookies off should be a best practice (some AV software even recommends it), but I can't guess how many users it actually affects.  Most of the users will probably just skip the extension if it doesn't work off the bat.

Now we wait, I guess ... :D

**Comment by z0rb** [comment]
I have removed the third party cookie white list, and also all cookies from the tracker and tested.
Mozilla seems to have fixed the underlying bug. I'll close this PR and the issue. If it is a false positive I'll reopen, but it seems ok.

**Comment by DASPRiD** [comment]
Thanks for keeping me in the loop, good job! :)

**Pull request closed without merging**
