### PR TITLE
Use Fetch-API to add referrer when downloading

### PR DESCRIPTION
**Pull request by felfert**
This extension does not work with some torrent sites which require a **Referer** header during torrent download. Unfortunately, **Referer** is one of the [forbidden Headers](https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name) that are not allowed to be set when using XMLHTTPRequest. There is however Mozilla's [Fetch-API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) which is considered safe and therefore allows just that.

This PR replaces the use of XMLHTTPRequest by fetch() for the download part and adds a Referer header.

Cheers
 -Fritz

### CODE REVIEW

**Comment by DASPRiD** [comment]
This looks good to me, thanks for your work! Wouldn't it make sense to also replace to other occurrences with the fetch API?

**Comment by felfert** [comment]
> This looks good to me, thanks for your work! Wouldn't it make sense to also replace to other occurrences with the fetch API?

Not really, as long as an upload without referrer is sufficient. (Which it is, apparently).

**Comment by DASPRiD** [comment]
Fair enough, I personally don't care for refactoring it either, since the extension just works.

**Comment by felfert** [comment]
Ok, then I'm eagerly waiting for a new release ;-)

**Pull request merged**
